#!/command/with-contenv bash
# shellcheck shell=bash

echo "
PUID=${PUID}
PGID=${PGID}
UMASK=${UMASK}
TZ=${TZ}
"

if [[ ! "${PUID}" -eq 0 ]] && [[ ! "${PGID}" -eq 0 ]]; then
    echo "Executing usermod..."
    mkdir "/tmp/home"
    usermod -d "/tmp/home" user
    usermod -o -u "${PUID}" user
    usermod -d "${CONFIG_DIR}" user
    rm -rf "/tmp/home"
    groupmod -o -g "${PGID}" user
else
    echo "Running as root is not supported, please set PUID and PGID."
    exit 1
fi

echo "Applying permissions to ${CONFIG_DIR}"
chmod "=rwx" "${CONFIG_DIR}"
chown user:user "${CONFIG_DIR}"

